language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install luaossl # optional dep for webhook test
  - luarocks install busted
  - luarocks install moonscript
  - luarocks make

script: 
  - busted

