language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2 CJSON=2.1.0
    - LUA=lua5.3 CJSON=2.1.0
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install luaossl # optional dep for webhook test
  - luarocks install lua-cjson $CJSON # fix for broken cjson library: https://github.com/openresty/lua-cjson/issues/36
  - luarocks install busted
  - luarocks install moonscript
  - luarocks make

script:
  - busted

